### ISSUE TITLE
Add User and Users compatibility

### ISSUE THREAD

**Issue by yckart** [IDT-media/Pages2JSON#3]
Would nice to have `toJSON` on `User` and `Users` instances. `User` already has it, since it extends `Page`, but results currently in `null`.

**Comment by Stikki** [comment]
Yup, because check for it is missing, you could test following:

From:

```
// Handle processwire internals
switch($value->className) {

    case 'Page':
        return $this->toPage($value);

    case 'Pageimage':
    case 'Pagefile':
        return array("url" => $value->url, "description" => $value->description);

    case 'Pagefiles':
    case 'Pageimages':
    case 'PageArray':
    case 'WireArray':
        return $this->toArray($value);

    case 'MapMarker':
        return array("lat" => $value->lat, "lng" => $value->lng, "zoom" => $value->zoom, "address" => $value->address);             
}
```

To:

```
// Handle processwire internals
switch($value->className) {

    case 'Page':
    case 'User':
        return $this->toPage($value);

    case 'Pageimage':
    case 'Pagefile':
        return array("url" => $value->url, "description" => $value->description);

    case 'Pagefiles':
    case 'Pageimages':
    case 'PageArray':
    case 'WireArray':
        return $this->toArray($value);

    case 'MapMarker':
        return array("lat" => $value->lat, "lng" => $value->lng, "zoom" => $value->zoom, "address" => $value->address);             
}

```

## 

Users is DAO unit, not actual container, so can't really serialize it, but this should serialize user correctly and not return null anymore.

Reason why all Page derived Object types ain't on list by default, as i want it to be more or less dummy proof and not cause errors, especially if some object type requires some special mapping.

Cheers for interest towards this module.

Will commit changes later today.

**Comment by Stikki** [comment]
This was just commited, finally! Closing issue.
